### ISSUE TITLE
Update version in composer.json

### ISSUE THREAD

**Issue by henri9813** [jzonta/FakerRestaurant#11]
Hello, 

Actually, when i download the package with composer, i have an outdated version, can you please, publish a release while increasing version number? 

Thanks.

**Comment by henri9813** [comment]
Sorry, i repoen the issue,

On packagist the lastest version is 1.0.0: https://packagist.org/packages/jzonta/faker-restaurant

``` 
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package jzonta/faker-restaurant ^1.1 exists as jzonta/faker-restaurant[1.0.0, dev-master] but these are rejected by your constraint.
``` 

Can you upgrade the package package version ? 
Can we automatize packagist upgrade ? 

Regards

**Comment by jzonta** [comment]
Hello, I did the update of the package, it is not a task I do frequently, so I do not know how to use very well, if you have a suggestion to automate, please can do.

**Comment by jzonta** [comment]
Hello, I did the update of the package, it is not a task I do frequently, so I do not know how to use very well, if you have a suggestion to automate, please can do.

**Comment by jzonta** [comment]
Long time without interaction
