### ISSUE TITLE
Short array syntax is allowed in php 5.4 Only..

### ISSUE THREAD

**Issue by henri9813** [jzonta/FakerRestaurant#12]
Hello,

I just update my forked version and i got this in phpStorm. 

I will propose a PR this day to fix this.

![image](https://user-images.githubusercontent.com/4645967/52704902-ed4c5480-2f81-11e9-92a8-708f8d45f0d0.png)

Regards

**Comment by jzonta** [comment]
This is not a syntax error, version 5.4 of php already supports array creation in this way.

See the documentation: https://secure.php.net/manual/en/language.types.array.php

**Comment by vishwakarma09** [comment]
@henri9813 in composer.json file, increase the php required version from <5.4 to something more recent like 7.2

"require": {
	-	"php": ">=5.3.7"
	+	"php": ">=7.2"
	},
