### ISSUE TITLE
Duplicate entries in arrays

### ISSUE THREAD

**Issue by henri9813** [jzonta/FakerRestaurant#13]
Hello,

They are some duplicated values
``` 
    protected static $dairyNames = [
        'Butter',
        'Egg',
        'Milk',
        'Cheese',
        'Sour cream',
        'Mozzarella',
        'Yogurt',
        'Cream',
        'Milk',
        'Custard',
    ];
``` 

Also, Cream and Custard are the same thing no ? 
And Egg is not a dairy product ?
Hot dog is not a meat ?

To avoid theses problems can we force array to be alphabetical sorted ?

**Comment by jzonta** [comment]
This is not a syntax error, version 5.4 of php already supports array creation in this way.

See the documentation: https://secure.php.net/manual/en/language.types.array.php

**Comment by jzonta** [comment]
You can make any corrections you think necessary and resubmit. 
Please remember to change the composer to a new version, currently it is in 1.1.0, you can change it to 1.1.1

 Thank you

**Comment by jzonta** [comment]
Long time without interaction
