### ISSUE TITLE
can't use specific language on laravel 6

### ISSUE THREAD

**Issue by haruyan** [jzonta/FakerRestaurant#26]
I'm trying to use id_ID language and keep getting this:

`Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'FakerRestaurant\Provider\id_ID\Restaurant' not found`

but it's okay when use en_US language, any solutions?

**Comment by jzonta** [comment]
Sorry, i do not publish version in Packagist. I solved problem, please update version in your composer.json to "jzonta/faker-restaurant": "~1.1.5"
